-- CREATING TABLES

CREATE TABLE EMPLOYEES_3(
	EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(90) NOT NULL,
    DEPARTMENT_ID INT,
    SALARY NUMERIC(10,2),
    JOINING_DATE DATE,
    MANAGER_ID INT
);

CREATE TABLE DEPARTMENTS_3(
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL
);

-- INSERTING DATA

INSERT INTO EMPLOYEES_3
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY, JOINING_DATE, MANAGER_ID)
VALUES
(101, 'Mahad', 'Farman', 1, 85000.00, '2023-01-15', NULL),
(102, 'Affan', 'Khan', 1, 65000.00, '2023-03-10', 101),
(103, 'Sarim', 'Ahmed', 2, 62000.00, '2023-05-20', 107),
(104, 'Ahat', 'Ali', 2, 78000.00, '2023-07-12', 107),
(105, 'Mustafa', 'Raza', 3, 70000.00, '2024-01-18', 108),
(106, 'Faika', 'Malik', 3, 65000.00, '2024-04-25', 108),
(107, 'Masahim', 'Ahmed', 1, 95000.00, '2022-08-15', NULL),
(108, 'Azkia', 'Rauf', 3, 80000.00, '2023-02-11', NULL),
(109, 'Muntaha', 'Saeed', NULL, 68000.00, '2023-06-19', NULL),
(110, 'Afif', 'Hassan', 2, 60000.00, '2024-02-05', 103);

SELECT * FROM employees_3;

INSERT INTO DEPARTMENTS_3
(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES
(1, 'Sales'),
(2, 'IT'),
(3, 'HR'),
(4, 'Finance');

SELECT * FROM departments_3;

-- SQL JOINS ASSINGMENT 

-- QUETIONS

-- 1. Write an SQL query to display employee names and their department names using
-- INNER JOIN.
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES_3 E
INNER JOIN
	DEPARTMENTS_3 D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 2. Write an SQL query to display all employees, including those without a department,
-- using LEFT JOIN.
SELECT * FROM EMPLOYEES_3 E
LEFT JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 3. Write an SQL query to display all departments, including those without employees,
-- using RIGHT JOIN.
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES_3 E RIGHT JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 4. Write an SQL query to display all records from Employees and Departments using
-- FULL OUTER JOIN.
SELECT * FROM EMPLOYEES_3 E 
FULL JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 5. Write an SQL query to display every employee with every department using
-- CROSS JOIN.
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES_3 E CROSS JOIN DEPARTMENTS_3 D;

-- 6. Write an SQL query to display employees and their managers using SELF JOIN.
SELECT E1.FIRST_NAME AS EMPLOYEES,
		E2.FIRST_NAME AS MANAGERS
FROM EMPLOYEES_3 E1 JOIN EMPLOYEES_3 E2
ON E1.MANAGER_ID =E2.EMPLOYEE_ID; 

-- 7. Find employees  working in the 'Sales' department using INNER JOIN.
SELECT E.FIRST_NAME,E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES_3 E INNER JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE DEPARTMENT_NAME = 'Sales';

-- 8. Display employee name and salary with department name.
SELECT E.FIRST_NAME, E.SALARY, D.DEPARTMENT_NAME
FROM EMPLOYEES_3 E INNER JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 9. Find departments with no employees.
SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS_3 D LEFT JOIN EMPLOYEES_3 E 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE EMPLOYEE_ID IS NULL;

-- 10. Find employees who are not assigned to any department.
SELECT FIRST_NAME,LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES_3
WHERE DEPARTMENT_ID IS NULL;


-- 11. Display employee IDs and department IDs using INNER JOIN.
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES_3 E INNER JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

-- 12. Find all managers and the employees reporting to them.
SELECT E1.FIRST_NAME AS REPORTING_EMPLOYEES,
		E2.FIRST_NAME AS MANAGERS
FROM EMPLOYEES_3 E1 JOIN EMPLOYEES_3 E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

-- 13. Count employees in each department using JOIN and GROUP BY.
SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID)
FROM DEPARTMENTS_3 D LEFT JOIN  EMPLOYEES_3 E
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

-- 14. Display only matching records between Employees and Departments.
SELECT * FROM EMPLOYEES_3 E INNER JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;


-- 15. Find the highest-paid employee in each department using JOIN.
SELECT  MAX(E.SALARY), D.DEPARTMENT_NAME
FROM EMPLOYEES_3 E RIGHT JOIN DEPARTMENTS_3 D
ON E.DEPARTMENT_ID =D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;